# POSTTEST 7
# IMPORT PACKAGE

In [27]:
import numpy as np
import tensorflow as tf


# Membuat random tensor dengan shape 5:5

In [28]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.28433853,  0.8922832 ,  0.8983451 ,  0.7163981 ,  0.34969485],
       [-0.37960768,  0.01531979,  0.27423722, -2.214901  , -0.08514621],
       [ 1.0113182 ,  0.6616626 ,  1.383323  , -0.40465203,  0.86142987],
       [-0.12589967, -1.418615  ,  2.0295074 ,  0.15304402,  0.13658497],
       [-0.49787143,  0.38847125, -0.4244715 ,  0.46214256, -0.5444318 ]],
      dtype=float32)>

# Membuat prime tensor list bilangan prima dengan shape 5:5

In [29]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], shape=[5, 5], dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

# Hasil dari perhitungan aritmetika 2 variable (Gunakan minimal 5 operator)

# Perhitungan aritmatika multiply (perkalian)


In [30]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[ -0.56867707   2.6768496    4.4917254    5.0147867    3.8466434 ]
 [ -4.9349       0.2604365    5.210507   -50.942722    -2.4692402 ]
 [ 31.350864    24.481516    56.71624    -17.400038    40.487206  ]
 [ -6.672683   -83.69828    123.79995     10.866125     9.970702  ]
 [-39.331844    32.243114   -37.77796     44.827827   -54.987614  ]], shape=(5, 5), dtype=float32)


# Perhitungan aritmatika divide (pembagian)


In [31]:
print(tf.divide(random_tensor, prime_tensor))


tf.Tensor(
[[-0.14216927  0.29742774  0.17966902  0.10234259  0.03179044]
 [-0.02920059  0.00090116  0.01443354 -0.09630004 -0.00293608]
 [ 0.03262317  0.01788277  0.03373959 -0.00941051  0.0183283 ]
 [-0.00237547 -0.02404432  0.03327061  0.00215555  0.00187103]
 [-0.00630217  0.00468038 -0.00476934  0.00476436 -0.00539041]], shape=(5, 5), dtype=float32)


# Perhitungan aritmatika add (pertambahan)


In [32]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[  1.7156615   3.8922832   5.898345    7.7163982  11.349695 ]
 [ 12.620392   17.01532    19.274237   20.785099   28.914854 ]
 [ 32.01132    37.661663   42.383324   42.59535    47.86143  ]
 [ 52.8741     57.581387   63.029507   71.153046   73.13658  ]
 [ 78.50213    83.38847    88.57553    97.46214   100.45557  ]], shape=(5, 5), dtype=float32)


# Perhitungan aritmatika substract (pengurangan)


In [33]:
print(tf.subtract(random_tensor,prime_tensor).numpy())


[[  -2.2843385   -2.1077168   -4.101655    -6.2836018  -10.650305 ]
 [ -13.379608   -16.98468    -18.725763   -25.214901   -29.085146 ]
 [ -29.988682   -36.338337   -39.616676   -43.40465    -46.13857  ]
 [ -53.1259     -60.418613   -58.970493   -70.846954   -72.86342  ]
 [ -79.49787    -82.61153    -89.42447    -96.53786   -101.54443  ]]


# Perhitungan aritmatika pow (pangkat)

In [34]:
print(tf.pow(random_tensor,prime_tensor).numpy())


[[ 8.0848403e-02  7.1040851e-01  5.8508104e-01  9.6845858e-02
   9.5627229e-06]
 [-3.3990286e-06  1.4102624e-31  2.1105780e-11 -8.7730216e+07
  -9.4361422e-32]
 [ 1.4174985e+00  2.3096874e-07  5.9960731e+05 -1.2720790e-17
   9.0227008e-04]
 [-0.0000000e+00 -9.1202765e+08  5.6341576e+18  0.0000000e+00
   0.0000000e+00]
 [-1.1810252e-24  8.2563274e-35 -7.5599596e-34  3.0427649e-33
  -2.1394018e-27]]


# Menampilkan nilai maksimal dari variable random_tensor

In [35]:
tf.argmax(random_tensor, axis=0)


<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 0, 3, 0, 2], dtype=int64)>

# Menampilkan nilai minimal dari variable random_tensor

In [36]:
tf.argmin(random_tensor, axis=0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 3, 4, 1, 4], dtype=int64)>

# Penggabungan variable random_tensor dan prime_tensor
# (Concatenation)

In [37]:
print("Size original pada data random dan prime tensor:",random_tensor.shape,prime_tensor.shape)
concated_tensor = tf.concat([random_tensor,prime_tensor],axis=0)
print("Size concatenated data:",concated_tensor.shape)


Size original pada data random dan prime tensor: (5, 5) (5, 5)
Size concatenated data: (10, 5)


# Sorting secara Descending variable random_tensor dan prime_tensor

In [38]:
print("input prime tensor:",prime_tensor.numpy())
print("input random tensor:",random_tensor.numpy())
sorted_random = tf.sort(random_tensor, direction = "DESCENDING")
print("hasil random tensor sorted dengan descending order:",sorted_random.numpy())
sorted_prime = tf.sort(prime_tensor, direction = "DESCENDING")
print("hasil prime tensor sorted dengan descending order:",sorted_prime.numpy())


input prime tensor: [[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]
input random tensor: [[-0.28433853  0.8922832   0.8983451   0.7163981   0.34969485]
 [-0.37960768  0.01531979  0.27423722 -2.214901   -0.08514621]
 [ 1.0113182   0.6616626   1.383323   -0.40465203  0.86142987]
 [-0.12589967 -1.418615    2.0295074   0.15304402  0.13658497]
 [-0.49787143  0.38847125 -0.4244715   0.46214256 -0.5444318 ]]
hasil random tensor sorted dengan descending order: [[ 0.8983451   0.8922832   0.7163981   0.34969485 -0.28433853]
 [ 0.27423722  0.01531979 -0.08514621 -0.37960768 -2.214901  ]
 [ 1.383323    1.0113182   0.86142987  0.6616626  -0.40465203]
 [ 2.0295074   0.15304402  0.13658497 -0.12589967 -1.418615  ]
 [ 0.46214256  0.38847125 -0.4244715  -0.49787143 -0.5444318 ]]
hasil prime tensor sorted dengan descending order: [[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]